# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/tictactoe_python"
    schedule:
      interval: "weekly"
    groups:
      python-minor:
        update-types:
          - minor
          - patch
  - package-ecosystem: "pip"
    directory: "/tictactoe_python/test"
    schedule:
      interval: "weekly"
    groups:
      python-minor-dev:
        update-types:
          - minor
          - patch
  - package-ecosystem: "cargo"
    directory: "/tictactoe_rust"
    schedule:
      interval: "weekly"
    groups:
      cargo-minor:
        update-types:
          - minor
          - patch
  - package-ecosystem: "bundler"
    directory: "/tictactoe_ruby"
    schedule:
      interval: "weekly"
    groups:
      bundler-minor:
        update-types:
          - minor
          - patch
  - package-ecosystem: "gomod"
    directory: "/tictactoe_go"
    schedule:
      interval: "weekly"
    groups:
      cargo-minor:
        update-types:
          - minor
          - patch
  - package-ecosystem: "maven"
    directory: "/tictactoe_java"
    schedule:
      interval: "weekly"
    groups:
      java-minor:
        update-types:
          - minor
          - patch
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      js-minor:
        update-types:
          - minor
          - patch
  - package-ecosystem: "gradle"
    directory: "/tictactoe_kotlin"
    schedule:
      interval: "weekly"
    groups:
      kotlin-minor:
        update-types:
          - minor
          - patch
  - package-ecosystem: "swift"
    directory: "/tictactoe_swift"
    schedule:
      interval: "weekly"
    groups:
      swift-minor:
        update-types:
          - minor
          - patch

  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`. (You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.)
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "40ants/setup-lisp"
    groups:
      actions-all:
        patterns:
          - "*"
