linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exhaustruct   # Should be useful in the future. No time now
    - forcetypeassert
    - funlen  # Should be usefull in the future. No time atm
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gocognit  # Similar to cyclop. Could be usefull
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - err113
    - goheader
    - mnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varnamelen  # Usefull for the future
    - whitespace
    - wrapcheck
    - zerologlint
  disable:
    - gci  # Broken for me
    - gofmt
    - gofumpt
    - goimports
    - forbidigo
    - dupl
    - wsl
    - nlreturn
    - copyloopvar  # Not running anyway because project supports 1.19

linters-settings:
  gosec:
    # Available rules: https://github.com/securego/gosec#available-rules
    excludes:
      - G404
  cyclop:
    # The maximal code complexity to report.
    # Default: 10
    max-complexity: 12
    # The maximal average package complexity.
    # If it's higher than 0.0 (float) the check is enabled
    # Default: 0.0
    package-average: 0.0
  varnamelen:
    ignore-names:
      - is
