[default.extend-words]
# Don't correct the acronym ot for overtime
ba = "ba"


[default]
extend-ignore-identifiers-re = [
    # Don't correct the name MAKARxJESUS
    "MAKAR.*",
    # Don't correct the id in notebook
    ".*ba355586.*",
]

[type.golangcilint]
extend-glob = [".golangci.yaml", "**/Main.storyboard", "**/MainMenu.xib"]
check-file  = false