# This workflow will compile the assembly version of tictactoe

name: Assembly

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tictactoe_assembly
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y nasm
    - name: Build
      run: |
        make build
