# This workflow will run the build on the C version of tictactoe

name: C

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tictactoe_c
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Build
      run: |
        make
    - name: Test
      run: |
        make test
    - name: Run
      run: |
        ./bin/tictactoe_c -X 0 -O 0
  python-ext:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tictactoe_c
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build
        run: |
          pip install setuptools
          make
      - name: Run Python
        run: make run_python
      - name: Create stubs
        run: |
          pip install mypy
          stubgen -p tictactoe_c -o stubs
      - name: Upload stubs
        uses: actions/upload-artifact@v4
        with:
            name: Stub-file-${{ matrix.python-version }}
            path: ./tictactoe_c/stubs/
