# This workflow will run carbon version of tictactoe

name: carbon

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tictactoe_carbon
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      - name: Set VERSION env
        run: echo "VERSION=$(date -d yesterday +0.0.0-0.nightly.%Y.%m.%d)" >> "$GITHUB_ENV"
      - name: Setup Carbon
        run: |
          sudo apt install libgcc-11-dev
          wget https://github.com/carbon-language/carbon-lang/releases/download/v${{ env.VERSION }}/carbon_toolchain-${{ env.VERSION }}.tar.gz
          tar -xvf carbon_toolchain-${{ env.VERSION }}.tar.gz
      - name: Compile
        run: |
          ./carbon_toolchain-${{ env.VERSION }}/bin/carbon compile --output=tictactoe_carbon.o tictactoe_carbon.carbon
      - name: Link
        run: |
          ./carbon_toolchain-${{ env.VERSION }}/bin/carbon link --output=tictactoe_carbon tictactoe_carbon.o
      - name: Run
        run: |
          ./tictactoe_carbon < input1.txt || true
          ./tictactoe_carbon < input2.txt || true
