# This workflow will compile the cobol version of tictactoe

name: cobol

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tictactoe_cobol
    steps:
    - name: Checkout repo
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
    - name: Setup Cobol
      uses: fabasoad/setup-cobol-action@bdd06ad15f6c2a9df376bc25acbdc361aea50831 # v1.6.2
    - name: Compile.
      run: |
        cobc -x tictactoe_cobol.cob
    - name: Run
      run: |
        ./tictactoe_cobol < input.txt
