# This workflow will run the tests on the C++ version of tictactoe

name: C++

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tictactoe_cpp
    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Lint with cpplint
      run: |
        pip install cpplint
        cpplint --filter=-build/include_subdir */*.cpp */*.hpp
    - name: Prepare cmake
      run: |
        cmake -S . -B build
    - name: Build
      run: |
        cmake --build build
    - name: Test
      run: |
        cd build && ctest
