# This workflow will run the tests on the c# version of tictactoe

name: C#

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tictactoe_csharp
    steps:
      - uses: actions/checkout@v5
      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
      - name: Build
        run: dotnet build Tictactoe.Lib
      - name: Test
        run: dotnet test Tictactoe.Tests
      - name: Run
        run: |
          cd Tictactoe.Prog
          dotnet run -- -X 4 -O 4
