# This workflow will run the tests on the c# version of tictactoe

name: C#

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tictactoe_csharp
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Setup dotnet
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
      - name: Build
        run: dotnet build Tictactoe.Lib
      - name: Test
        run: dotnet test Tictactoe.Tests
      - name: Run
        run: |
          cd Tictactoe.Prog
          dotnet run -- -X 4 -O 4
