# This workflow will run the tests on the c# version of tictactoe

name: C#

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tictactoe_csharp
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Setup dotnet
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
      - name: Build
        run: dotnet build Tictactoe.Lib
      - name: Test
        run: dotnet test Tictactoe.Tests
      - name: Run
        run: |
          cd Tictactoe.Prog
          dotnet run -- -X 4 -O 4
