# This workflow will run the tests on the D version of tictactoe

name: D

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tictactoe_d
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Setup D
        uses: dlang-community/setup-dlang@0a7469b93f791d83f30932c6fd105796c6966e20 # v2.0.0
        with:
          compiler: dmd
      - name: Run tests
        run: dub test
      - name: Run the game
        run: dub run -- --X-strength=4 --O-strength=4
