# This workflow will run the tests on the D version of tictactoe

name: D

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tictactoe_d
    steps:
      - uses: actions/checkout@v4
      - name: Setup D
        uses: dlang-community/setup-dlang@v2
        with:
          compiler: dmd
      - name: Run tests
        run: dub test
      - name: Run the game
        run: dub run -- --X-strength=4 --O-strength=4
