# This workflow will run the tests on the dart version of tictactoe

name: dart

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./tictactoe_dart
    steps:
    - name: Checkout repo
      uses: actions/checkout@v5
    - uses: subosito/flutter-action@v2
      with:
        cache: true
        channel: stable
    - name: Setup flutter dependencies
      run: |
        flutter --version
        flutter doctor --verbose
        flutter pub get
    - name: Build for windows
      run: |
        flutter config --enable-windows-desktop
        flutter build windows
    - name: Lint
      run: |
        flutter analyze
    - name: Test
      run: |
        choco install lcov
        flutter test --coverage
        perl C:\ProgramData\chocolatey\lib\lcov\tools\bin\genhtml -o coverage\html coverage\lcov.info
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: ./tictactoe_dart/coverage/html/
