# This workflow will run the tests on the dart version of tictactoe

name: dart

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./tictactoe_dart
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: 'oracle' # See 'Supported distributions' for available options
        java-version: '20'
        cache: 'gradle'
    - uses: subosito/flutter-action@v2
      with:
        cache: true
        channel: 'stable' # or: 'beta', 'dev' or 'master'
    - run: flutter pub get
    - run: flutter build apk
    - run: flutter build appbundle
    - run: flutter build web
    - run: flutter config --enable-windows-desktop
    - run: flutter build windows
    - run: flutter test
