# This workflow will run stuff on the dreamberd version of tictactoe.

name: dreamberd

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./tictactoe_dreamberd
    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Checkout repo
      uses: actions/checkout@v5
    - name: Install dependencies
      run: |
        pip install "dreamberd[input] @ git+https://github.com/JanEricNitschke/dreamberd-interpreter.git"
        pip install pynput
    - name: Run
      run: |
        set LC_CTYPE="de_DE.UTF-8"
        set LANG="de_DE.UTF-8"
        set LC_ALL="de_DE.UTF-8"
        Set-Culture de-DE
        set PYTHONUNBUFFERED=1
        python simulate_key_presses.py --win & dreamberd tictactoe.db
        python simulate_key_presses.py --draw & dreamberd tictactoe.db
