# This workflow will run the tests on the Elixir version of tictactoe

name: Elixir

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tictactoe_elixir
    steps:
      - uses: actions/checkout@v4
      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ">0"
          otp-version: ">0"
      - name: Run formatter
        run: mix format --check-formatted
      - name: Install dependencies
        run: mix deps.get
      - name: Run static analysis
        run: mix dialyzer
      - name: Run tests
        run: mix test --no-start
      - name: Run the game
        run: mix run -- --x-strength 4 --o-strength 4
