# This workflow will run stuff on the Erlang version of tictactoe

name: Erlang

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tictactoe_erlang
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Setup Erlang
        uses: erlef/setup-beam@fc68ffb90438ef2936bbb3251622353b3dcb2f93 # v1.24.0
        with:
          otp-version: ">0"
      - name: Compile lib
        run: erlc tictactoe.erl
      - name: Run script
        run: escript tictactoe.escript 4 4
