# This workflow will run the tests on the generic version of tictactoe

name: generic

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tictactoe_generic
    steps:
    - name: Checkout repo
      uses: actions/checkout@v5
    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
          toolchain: stable
    - name: Install generic
      run: cargo install generic-lang
    - name: Test
      run: generic --test tests/
