# This workflow will run the tests on the generic version of tictactoe

name: generic

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: main/tictactoe_generic
    steps:
    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
          toolchain: stable
    - name: Checkout generic
      uses: actions/checkout@v4
      with:
        repository: JanEricNitschke/generic-lang
        path: generic-lang
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        path: main
    - name: Install generic
      run: cargo install --path .
      working-directory: generic-lang
    - name: Test
      run: generic tests/test_tictactoe.gen
