# This workflow will run the tests on the go version of tictactoe

name: go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tictactoe_go
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        working-directory: ./tictactoe_go
        version: v1.53
    - name: Build
      run: go build
    - name: Test
      run: |
        go test -covermode=count -coverprofile=coverage.out
        go tool cover -html=coverage.out -o coverage.html
    - name: Fuzz
      run: |
        go test -fuzz=FuzzSwapPlayer -fuzztime 30s
        go test -fuzz=FuzzGetEmptyCells -fuzztime 30s
        go test -fuzz=FuzzRandomMove -fuzztime 30s
        go test -fuzz=FuzzMinMax -fuzztime 60s
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: ./tictactoe_go/coverage.html
