# This workflow will run lints on the javascript version of tictactoe

name: javascript

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Prettier
        uses: actionsx/prettier@3d9f7c3fa44c9cb819e68292a328d7f4384be206 # v3
        with:
          # prettier CLI arguments.
          args: --check "./tictactoe_javascript/**.{css,js}"
      - name: Install eslint
        run: |
          npm i eslint --save-dev
          npm install @babel/core @babel/eslint-parser --save-dev
          npm install
      - name: Lint
        run: ./node_modules/.bin/eslint .
