# This workflow will compile the julia version of tictactoe

name: julia

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tictactoe_julia
    steps:
    - name: Checkout repo
      uses: actions/checkout@v5
    - name: Setup Julia
      uses: julia-actions/setup-julia@v2
    - name: Compile, test and run.
      run: |
        julia --project=. test/runtests.jl
        julia --project=. test/runexample.jl -X 3 -O 3
