# This workflow will compile the julia version of tictactoe

name: julia

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tictactoe_julia
    steps:
    - name: Checkout repo
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
    - name: Setup Julia
      uses: julia-actions/setup-julia@fa02766e078afaaf09b14210362cee14137e6a32 # v3.0.2
    - name: Compile, test and run.
      run: |
        julia --project=. test/runtests.jl
        julia --project=. test/runexample.jl -X 3 -O 3
