# This workflow will run the tests on the mojo version of tictactoe

name: Mojo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tictactoe_mojo
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: prefix-dev/setup-pixi@5185adfbffb4bd703da3010310260805d89ebb11 # v0.9.6
        with:
          manifest-path: ./tictactoe_mojo/pixi.toml
      - name: Build
        run: pixi run mojo build main.mojo
      - name: Run
        run: ./main
      - name: Test
        run: pixi run mojo run -I . test/test_game.mojo
