# This workflow will run the tests on the mojo version of tictactoe

name: Mojo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tictactoe_mojo
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.11
        with:
          manifest-path: ./tictactoe_mojo/pixi.toml
      - name: Build
        run: pixi run mojo build main.🔥
      - name: Run
        run: ./main
      - name: Test
        run: pixi run mojo test -I . test
