# This workflow will run the tests on the mojo version of tictactoe

name: Mojo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tictactoe_mojo
    steps:
      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
        with:
          manifest-path: ./tictactoe_mojo/pixi.toml
      - name: Build
        run: pixi run mojo build main.mojo
      - name: Run
        run: ./main
      - name: Test
        run: pixi run mojo run -I . test/test_game.mojo
