# This workflow will do stuff for the nim version.

name: nim

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tictactoe_nim
    steps:
    - name: Checkout repo
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - uses: jiro4989/setup-nim-action@cb1fc1270b117457dd0d9f610ec981fad3369cec # v2.3.0
      with:
        nim-version: 'stable'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Compile
      run: nimble build
    - name: Test
      run: nimble test
    - name: Run
      run: ./tictactoe_nim --X=4 --O=4
