# This workflow will run the nix version of tictactoe

name: Nix

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tictactoe_nix
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: cachix/install-nix-action@ab739621df7a23f52766f9ccc97f38da6b7af14f # v31.10.5
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-instantiate --eval tictactoe.nix --read-write-mode | xargs printf "%b"
