# This workflow will run stuff on the perl version of tictactoe

name: Perl

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tictactoe_perl
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: shogo82148/actions-setup-perl@53e33bb27be492a926eee378e8a5f7ff6618b061 # v1.43.1
        with:
          perl-version: "5.40"
      - name: Check
        run: perl -c tictactoe.pl
      - name: Test
        run: perl test_tictactoe.pl
      - name: Run
        run: perl tictactoe.pl -X 4 -O 4
