# This workflow will run stuff on the perl version of tictactoe

name: Perl

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tictactoe_perl
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: shogo82148/actions-setup-perl@a198315ec4e9244f206879ea7b63078003aec8a6 # v1.41.1
        with:
          perl-version: "5.40"
      - name: Check
        run: perl -c tictactoe.pl
      - name: Test
        run: perl test_tictactoe.pl
      - name: Run
        run: perl tictactoe.pl -X 4 -O 4
