# This workflow will run stuff on the perl version of tictactoe

name: Perl

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tictactoe_perl
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: shogo82148/actions-setup-perl@5a2f3b681f2e2fa0db6cc52c7608d9916527aa58 # v1.40.0
        with:
          perl-version: "5.40"
      - name: Check
        run: perl -c tictactoe.pl
      - name: Test
        run: perl test_tictactoe.pl
      - name: Run
        run: perl tictactoe.pl -X 4 -O 4
