# This workflow will run stuff on the piet version of tictactoe.

name: piet

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tictactoe_piet
    steps:
    - name: Checkout repo
      uses: actions/checkout@v5
    - name: Install dependencies
      run: |
        cargo install --locked --git 'https://github.com/your-diary/piet_programming_language'
    - name: Run
      run: |
        piet_programming_language tictactoe.png < input1.txt
        piet_programming_language tictactoe.png < input2.txt
