# This workflow will run stuff on the piet version of tictactoe.

name: piet

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tictactoe_piet
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        cargo install rpiet
    - name: Run
      run: |
        rpiet tictactoe.png < input1.txt
        rpiet tictactoe.png < input2.txt
