# This workflow will run the tests on the python version of tictactoe

name: Python

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tictactoe_python
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Checkout repo
        uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Installation
        run: |
          uv sync --group dev
      - name: Lint with ruff
        uses: astral-sh/ruff-action@v3
      - name: Check formatting with ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check"
      - name: Typecheck with pyright
        uses: jakebailey/pyright-action@v2
        with:
          working-directory: ./tictactoe_python
      - name: Thorough check with pylint
        run: uv run pylint tictactoe/
      - name: Test with pytest
        run: |
          uv run coverage run -m pytest --durations=10
          uv run coverage report -m
          uv run coverage json
          uv run coverage html
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report-${{ matrix.python-version }}
          path: ./tictactoe_python/htmlcov/
