# This workflow will run the tests on the ruby version of tictactoe

name: Ruby

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tictactoe_ruby
    steps:
    - name: Checkout repo
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Set up Ruby
      uses: ruby/setup-ruby@003a5c4d8d6321bd302e38f6f0ec593f77f06600 # v1.319.0
      with:
        ruby-version: ruby
        bundler-cache: False
        working-directory: ./tictactoe_ruby
    - name: Install dependencies
      run: bundle install
    - name: Run the default task
      run: bundle exec rake
