# This workflow will run the tests on the ruby version of tictactoe

name: Ruby

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tictactoe_ruby
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.1.3"
        bundler-cache: False
        working-directory: ./tictactoe_ruby
    - name: Install dependencies
      run: bundle install
    - name: Run the default task
      run: bundle exec rake
