# This workflow will run the tests on the ruby version of tictactoe

name: Ruby

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tictactoe_ruby
    steps:
    - name: Checkout repo
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Set up Ruby
      uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1.314.0
      with:
        ruby-version: ruby
        bundler-cache: False
        working-directory: ./tictactoe_ruby
    - name: Install dependencies
      run: bundle install
    - name: Run the default task
      run: bundle exec rake
