# This workflow will run the tests on the rust version of tictactoe

name: rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tictactoe_rust
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Lint
      run: |
        rustup component add clippy
        # Run normal configuration and fail on default warnings
        cargo clippy -- -D warnings
        # Run pedantic but do not fail
        cargo clippy -- -W clippy::all -W clippy::pedantic -W clippy::nursery -W clippy::cargo
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
