# This workflow will run stuff on the shakespeare version of tictactoe.

name: shakespeare

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tictactoe_shakespeare
    steps:
    - name: Set up Python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
      with:
        python-version: "3.12"
    - name: Checkout repo
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Install dependencies
      run: |
        pip install shakespearelang
    - name: Run
      run: |
        shakespeare run tictactoe.spl < input1.txt
        shakespeare run tictactoe.spl < input2.txt
