# This workflow does stuff on the smalltalk version

name: smalltalk

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tictactoe_smalltalk
    steps:
      - uses: actions/checkout@v5
      - uses: hpi-swa/setup-smalltalkCI@v1
        id: smalltalkci
        with:
          smalltalk-image: 'Squeak64-trunk'
      - run: echo "SmalltalkCI is ready"
