# This workflow does stuff on the smalltalk version

name: smalltalk

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tictactoe_smalltalk
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: hpi-swa/setup-smalltalkCI@999b788246c9dca7ac8e4c606caade213eb3906e # v1.6.0
        id: smalltalkci
        with:
          smalltalk-image: 'Squeak64-trunk'
      - run: echo "SmalltalkCI is ready"
