# This workflow will run the tests on the swift version of tictactoe

name: swift

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./tictactoe_swift
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: "5.10"
    - name: Build
      run: swift build
    - name: Test
      run: swift test
