# This workflow will run the tests on the swift version of tictactoe

name: swift

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./tictactoe_swift
    steps:
    - name: Checkout repo
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - uses: swift-actions/setup-swift@364295d9c23900ce04d4e5cc708387921b4e50f9 # v3
    - name: Build
      run: swift build
    - name: Test
      run: swift test
