# This workflow will run the tests on the swift version of tictactoe

name: swift

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./tictactoe_swift
    steps:
    - name: Checkout repo
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - uses: swift-actions/setup-swift@7ca6abe6b3b0e8b5421b88be48feee39cbf52c6a # v2.4.0
    - name: Build
      run: swift build
    - name: Test
      run: swift test
