# This workflow will run the tests on the swift version of tictactoe

name: swift

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./tictactoe_swift
    steps:
    - name: Checkout repo
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
    - uses: swift-actions/setup-swift@364295d9c23900ce04d4e5cc708387921b4e50f9 # v3
    - name: Build
      run: swift build
    - name: Test
      run: swift test
