# This workflow will run the tests on the zig version of tictactoe

name: zig

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tictactoe_zig
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup zig
      uses: goto-bus-stop/setup-zig@v2
    - name: Check formatting
      run: zig fmt --check src/*.zig
    - name: Build
      run: zig build install
    - name: Test
      run: zig build test
