# This workflow will run the tests on the zig version of tictactoe

name: zig

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tictactoe_zig
    steps:
    - name: Checkout repo
      uses: actions/checkout@v5
    - name: Setup zig
      uses: mlugg/setup-zig@v2
      with:
        version: latest
    - name: Check formatting
      run: zig fmt --check src/*.zig
    - name: Build
      run: zig build install
    - name: Test
      run: zig build test
    - name: Run
      run: |
        ./zig-out/bin/tictactoe_zig < input1.txt
        ./zig-out/bin/tictactoe_zig < input2.txt
        ./zig-out/bin/tictactoe_zig < input3.txt
        ./zig-out/bin/tictactoe_zig < input4.txt
